POST http://localhost:3001/api/items/1
Content-Type: application/json

{
  "productName":"Better Fruits",
  "annualSubscriptions":100,
  "monthlySubscriptions":10
}

### 

GET http://localhost:3001/api/items

###

GET http://localhost:3001/api/items/ccc3f8c6-cd6a-43ad-8af1-0aae0ce34622

###

PUT http://localhost:3001/api/items/ccc3f8c6-cd6a-43ad-8af1-0aae0ce34622
Content-Type: application/json

{
  "productName":"Better Vegetables",
  "annualSubscriptions":200,
  "monthlySubscriptions":20
}

###

DELETE http://localhost:3001/api/items/ccc3f8c6-cd6a-43ad-8af1-0aae0ce34622